### ISSUE TITLE
Definition of `\@xendnotenext`

### ISSUE THREAD

**Issue by gusbrs** [rf-latex/endnotes#11]
`\@xendnotenext` is being defined twice at:

https://github.com/rf-latex/endnotes/blob/1a45bef9bf708ea9154845453cb4875696b6930e/endnotes.sty#L367-L375

I know, harmless, but for the record.

**Comment by davidcarlisle** [comment]
Thanks I deleted it here, so it'll be fixed next time, I don't think I'll push out a release to ctan for this though as, as you say it doesn't affect the behaviour in any way.

**Comment by gusbrs** [comment]
Thank you! And, of course, for the next release, whenever it comes for due reason.
